name: Laravel

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  deploy:
    name: Deploy to AWS (EC2)
    runs-on: 68022573e1118.xvest1.ru
    steps:
      - name: executing remote ssh commands using private key
        uses: appleboy/ssh-action@v1.1.0
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.KEY }}
          script:
            cd /var/www/nt-laravel-chat-app
            sudo docker compose down
            sudo git reset --hard
            sudo git pull
            sudo docker compose up -d --build
            sleep 5
            sudo docker exec chat_app php artisan migrate
            sudo docker exec chat_app php artisan optimize
            sudo docker exec chat_app php artisan reverb:install
            sudo docker exec chat_app php artisan reverb:restart
            sudo docker exec chat_app php artisan reverb:start
            sudo docker exec chat_app php artisan queue:listen
            echo "Deploy Completed!"
